spring:
  application:
    name: springcloud-feigin


server:
  port: 8082

eureka:
  client:
    service-url:
      defaultZone: http://localhost:1111/eureka/

feign:
  circuitbreaker:
    enabled: true



